services:
  notification-dispatcher:
    image: devio95/notification-dispatcher
    container_name: notification-dispatcher
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitMQ_HostName=rabbitmq
      - NotifyX_ConnectionString=Server=database; Port=5432; Database=NotifyX; User ID=postgres; Password=admin
    networks:
      - notification-network
    depends_on:
      - rabbitmq
 
  notification-executioner:
    image: devio95/notification-executioner
    container_name: notification-executioner
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitMQ_HostName=rabbitmq
      - NotifyX_ConnectionString=Server=database; Port=5432; Database=NotifyX; User ID=postgres; Password=admin
    networks:
      - notification-network
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - notification-network

  database:
    image: postgres:latest
    container_name: database
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=NotifyX
    networks:
      - notification-network

networks:
  notification-network:
    driver: bridge

volumes:
  pgdata:    