services:
  notification-dispatcher:
    image: devio95/notification-dispatcher
    container_name: notification-dispatcher
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitMQ_HostName=rabbitmq
      - NotifyX_ConnectionString=Server=database; Port=5432; Database=NotifyX; User ID=postgres; Password=admin
    networks:
      - notification-network
    depends_on:
      - rabbitmq
 
  notification-executioner:
    image: devio95/notification-executioner
    container_name: notification-executioner
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitMQ_HostName=rabbitmq
      - NotifyX_ConnectionString=Server=database; Port=5432; Database=NotifyX; User ID=postgres; Password=admin
    networks:
      - notification-network
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - notification-network

  database:
    image: postgres:latest
    container_name: database
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=NotifyX
    networks:
      - notification-network

  keycloak-db:
    image: postgres:latest
    container_name: keycloak-db
    restart: unless-stopped
    ports:
        - "5433:5432"
    volumes:
        - keycloak_db_data:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=keycloak123
    networks:
        - notification-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak123
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
    command: ["start-dev"]
    networks:
      - notification-network
    depends_on:
      - keycloak-db

networks:
  notification-network:
    driver: bridge

volumes:
  pgdata:    
  keycloak_db_data:
  keycloak_data: